grade(engineering_drawing_1, c).
grade(engineering_drawing_2, a).
grade(statics, b).
grade(dynamics, c).
grade(differentiation, a).
grade(integration, b).
grade(computer_principles, b).
grade(physics_light_heat, a).
grade(physics_electricity_substances, d).
grade(principles_manufacturing, a).
grade(engineering_chemistry, f).
grade(technical_english, b).
interest(programming, 1).
interest(drawing, 5).
interest(math, 2).
interest(mechanics, 5).
interest(electronics, 1).
trait(creative, 5).
trait(analytical, 1).
trait(team-oriented, 1).
trait(physical_work, 4).
trait(visual_thinking, 2).